__title__ = "nfsclient"
__description__ = "NFSv3 client"
__version__ = "0.0.1"
__license__ = "MIT"
__url__ = "https://github.com/Jayson-Fong/python-nfsclient"
__author__ = "Jayson Fong"
__author_email__ = "jayson.fong@gatech.edu"
